# Generated by Django 2.2 on 2021-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='tmp/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
