# Generated by Django 2.2 on 2021-03-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(max_length=50),
        ),
    ]
