# Generated by Django 2.2 on 2021-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210311_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='summary',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
