# Generated by Django 2.2 on 2021-03-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fileupload_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='summary',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
